export const FETCHING = "IS_FETCHING";
export const ERROR = "ERROR_FETCH_CHARACTERS";
export const SUCCESS = "SUCCESS_FETCH_CHARACTERS";

export const FETCHING_CHAR = "IS_FETCHING_CHAR";
export const ERROR_CHAR = "ERROR_FETCH_CHARACTERS_CHAR";
export const SUCCESS_CHAR = "SUCCESS_FETCH_CHARACTERS_CHAR";

